name: Pylint

on:
  pull_request:
    branches: [main]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pylint
        run: |
          pylint --rcfile=.pylintrc **/*.py
